---
# yum_repository module does not allow to only enable a yum_repository
# so I deploy full repo file instead
- name: "Enable PowerTools repository"
  copy:
    src: CentOS-PowerTools.repo
    dest: "/etc/yum.repos.d/CentOS-PowerTools.repo"
    owner: "root"
    group: "root"
    mode: "0644"
  when: ansible_facts['distribution_major_version'] == "8"

- name: "Install prerequisite packages"
  package:
    name:
      - "gcc"
      - "make"
      - "perl"
      - "kernel-devel-{{ ansible_kernel }}"
      - "kernel-headers-{{ ansible_kernel }}"
      - "elfutils-libelf-devel"
      - "xorg-x11-xauth"
      - "xorg-x11-apps"
    state: present

- name: "Add VirtualBox repository"
  yum_repository:
    name: "virtualbox"
    description: "OEL / RHEL / CentOS-$releasever / $basearch - VirtualBox"
    baseurl: "http://download.virtualbox.org/virtualbox/rpm/el/$releasever/$basearch"
    gpgkey: "https://www.virtualbox.org/download/oracle_vbox.asc"
    gpgcheck: "yes"
    repo_gpgcheck: "yes"

- name: Import VirtualBox repo GPG key
  rpm_key:
    state: present
    key: https://www.virtualbox.org/download/oracle_vbox.asc

- name: "Install VirtualBox-{{ virtualbox_version }}"
  yum:
    name: "VirtualBox-{{ virtualbox_version }}"
    state: present
