---
- name: "Check OS version"
  fail:
    msg: "OS Version( {{ ansible_distribution }}{{ ansible_distribution_major_version }} ) is not certified for the role"
  when:
    - ansible_facts['distribution'] != "CentOS"
    - ansible_facts['distribution_major_version'] != "7" or ansible_facts['distribution_major_version'] != "8"

- name: Get CPU Virtualization Support
  shell:
    cmd: "lscpu | grep -w 'Virtualization type:' | egrep -w 'AMD-V|VT-x|full' | sort | uniq | wc -l"
  args:
    warn: no
  changed_when: no
  register: cpuinfo_output

- name: Check CPU Virtualization Support
  fail:
    msg: "CPU does not support virtualization"
  when:
    - cpuinfo_output.stdout != "1"

- name: Running tasks require privilege
  block:
    - name: "Install yum-utils"
      package:
        name: yum-utils
        state: present

    - name: "Upgrade system"
      yum:
        name: '*'
        state: latest

    - name: "Check if reboot is required"
      shell: /usr/bin/needs-restarting -r
      ignore_errors: "yes"
      register: needs_restarting

    - name: "Reboot server if needed"
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when: needs_restarting.rc == 1
  become: true
